### PR TITLE
Create cache component + More

### PR DESCRIPTION
**Pull request by Nazgaul**
Implement cache model. gives the ability to add a different cache other then file ( redis,sql etc) all you have to do is to implement ITldCacheProvider.
Refactor domainparser. added Get(Uri uri) to receive already well defined url.
Fix Get(string domain)
if the domain already contains (https) do not add.

### CODE REVIEW

**Comment by tinohager** [comment]
Which other cache you have planed?
Change the main method from string to uri is a bad idea it is a breaking change. When then it makes sense to overload the method...

**Comment by Nazgaul** [comment]
The other cache I thought is redis. All I have to do is to implement the interface and pass it to the code. No need for the package to implement that.
The uri I overload the function. String method only transfer to uri and pass it to the uri method

**Comment by Nazgaul** [comment]
Kinda think about it. The code maybe should implement in memory cache and let the person who uses the code to implement which cache he want

**Comment by tinohager** [comment]
I have add your logic after a cleanup in a own pull request.

**Pull request closed without merging**
